export const jojoProducts = [
  [
    {
      name: 'Шницель с авокадо',
      image: require('../assets/shnitsel.png'),
      price: 50,
      count: 1,
      weight: 400,
    },
    {
      name: 'Котлета с овощами',
      image: require('../assets/kotleta.png'),
      price: 55,
      count: 1,
      weight: 400,
    },
    {
      name: 'Теплый салат',
      image: require('../assets/tepliy_salat.png'),
      price: 35,
      count: 1,
      weight: 380,
    },
    {
      name: 'Блины с черникой',
      image: require('../assets/blini_s_chernikoy.png'),
      price: 40,
      count: 1,
      weight: 280,
    },
    {
      name: 'Макароны с овощами',
      image: require('../assets/makaroni.png'),
      price: 65,
      count: 1,
      weight: 280,
    },
  ],
  [
    {
      name: 'Уха',
      image: require('../assets/uxa.png'),
      price: 35,
      count: 1,
      weight: 360,
    },
    {
      name: 'Рамэн',
      image: require('../assets/ramen.png'),
      price: 50,
      count: 1,
      weight: 400,
    },
    {
      name: 'Куринный бульйон',
      image: require('../assets/kurinniy_bulyon.png'),
      price: 55,
      count: 1,
      weight: 310,
    },
    {
      name: 'Томатный суп',
      image: require('../assets/tomatniy_sup.png'),
      price: 55,
      count: 1,
      weight: 300,
    },
    {
      name: 'Грибной суп',
      image: require('../assets/gribnoy_sup.png'),
      price: 40,
      count: 1,
      weight: 300,
    },
  ],
  [
    {
      name: 'Брауни',
      image: require('../assets/brauni.png'),
      price: 25,
      count: 1,
      weight: 160,
    },
    {
      name: 'Панкейки с фруктами',
      image: require('../assets/pankeyki.png'),
      price: 15,
      count: 1,
      weight: 150,
    },
    {
      name: 'Блины с черникой',
      image: require('../assets/blini.png'),
      price: 25,
      count: 1,
      weight: 160,
    },
    {
      name: 'Чизкейк с манго',
      image: require('../assets/chizkeyk.png'),
      price: 15,
      count: 1,
      weight: 200,
    },
    {
      name: 'Рол Сладкий',
      image: require('../assets/rol.png'),
      price: 35,
      count: 1,
      weight: 180,
    },
  ],
];

export const allJojoProducts = [
  {
    name: 'Шницель с авокадо',
    image: require('../assets/shnitsel.png'),
    price: 50,
    count: 1,
    weight: 400,
  },
  {
    name: 'Котлета с овощами',
    image: require('../assets/kotleta.png'),
    price: 55,
    count: 1,
    weight: 400,
  },
  {
    name: 'Теплый салат',
    image: require('../assets/tepliy_salat.png'),
    price: 35,
    count: 1,
    weight: 380,
  },
  {
    name: 'Блины с черникой',
    image: require('../assets/blini_s_chernikoy.png'),
    price: 40,
    count: 1,
    weight: 280,
  },
  {
    name: 'Макароны с овощами',
    image: require('../assets/makaroni.png'),
    price: 65,
    count: 1,
    weight: 280,
  },
  {
    name: 'Уха',
    image: require('../assets/uxa.png'),
    price: 35,
    count: 1,
    weight: 360,
  },
  {
    name: 'Рамэн',
    image: require('../assets/ramen.png'),
    price: 50,
    count: 1,
    weight: 400,
  },
  {
    name: 'Куринный бульйон',
    image: require('../assets/kurinniy_bulyon.png'),
    price: 55,
    count: 1,
    weight: 310,
  },
  {
    name: 'Томатный суп',
    image: require('../assets/tomatniy_sup.png'),
    price: 55,
    count: 1,
    weight: 300,
  },
  {
    name: 'Грибной суп',
    image: require('../assets/gribnoy_sup.png'),
    price: 40,
    count: 1,
    weight: 300,
  },
  {
    name: 'Брауни',
    image: require('../assets/brauni.png'),
    price: 25,
    count: 1,
    weight: 160,
  },
  {
    name: 'Панкейки с фруктами',
    image: require('../assets/pankeyki.png'),
    price: 15,
    count: 1,
    weight: 150,
  },
  {
    name: 'Блины с черникой',
    image: require('../assets/blini.png'),
    price: 25,
    count: 1,
    weight: 160,
  },
  {
    name: 'Чизкейк с манго',
    image: require('../assets/chizkeyk.png'),
    price: 15,
    count: 1,
    weight: 200,
  },
  {
    name: 'Рол Сладкий',
    image: require('../assets/rol.png'),
    price: 35,
    count: 1,
    weight: 180,
  },
];
